language: minimal

env:
  global:
    - secure: q2ryLqwv6M/+pf9nKBx2WSruC/x7a8od31uoukkgOTsQhK5PXvVzGNxsQSmXrk9YD8fpQHFQrlo0y2951ngwmCfu4VzA8CSIo7QAZ5zgMOUouKBPEN8ONNdk0WQlmbqYMzUkFZau5flxIjQLWix6jt4n9H78M/w7w7iH0qLSyCWqgO7dYwTY6/MmKFyJ/4kiD2Qv/d6uby4qyAi14jx70gS8eE4zaR074OMFK3/+FJENEmhdH+lZKUaLxTr6kPy65FraG/6l+0T0B3l9YvSDm/eviGyPhKK3sTmMg+2YZNucYLXPkAyk8netaBh6r6kWtWcHsUV7ULXK4JhYnc8XfZnUKqg27Qr0XoL/4IdtCoyBXUaZPLI937Rj+6DxhWcBCrVkKJZX9LZtvBTabKQ+Mj67vuGdifA9aIB252Wg855AUuynuDBucXv4IyZwPEQPX6nQQO1r/BjiuW/B3/W3Wtqcorh5wfeI73Kcl0QbG/gyPaaSj0wPKHIEdzRF+CagDABBzRtSDSSEMEzInamQ1INsl515iTmvNVQs0EkHXdc6DXH8PR74hsrwH5PDE5Qdum/ZnHlN9KebfifHKq3rx55k2PlAA0l40PG0fleliGOIS2U9Rh+wgV8XQ3zVJOJcb0agQ+7Mibqz0EuIy9cgGqKuAXNygEp6r0r3Qwot7IE=
    - secure: JMLQHwCurfl3dQz+AZODrbB6nzp2jfHkxyEt665O9Mgqq7IULTJ5/VzbYf5diJyJSSUgpdAud9bL00SSn7PD0aTRCHptLES1vej5nHqQ9EDyicO8BcIchZil8NgDAsDub8WJLucgf5a2KmLzoUx3hzVHdgZBma16kKQKtGWXGEbe+EDbON2K7qPRVqBebMC4p3LJ3YtReNb3Vwz0ElUf3DLovW6luUXKl1O7Li7E1aTY9LqGNkqcrlfz4nzNp+JqklGrIbL0IzPp3wwuJgbEAIXhJeHo5y8RAL/i6mc8KqXpXrcPbpL+i3KEjESz03bJAAQKK+fcxTUF7a3uHU5guGzFowXMbaeKqTqKEwERnmuB5I9JgoQqOPz/+/gIIk5u25kSJ3RY/sSxXIPoMbMIJzmUHEoyyG+cHGr/84wWhgLT6Xjp+mXF72wq4F9zGo2FqDw58gevVBFBJ8VlIvi7npRIgzfY37wI/a+wnAHhBLuK258Ye9OhkDIkSD2pQ8Kyw4YLWt8Z9NfG5eKb++Mmt1sQGSB3lFPCamxnO8R89YWenSUvzkrIXalCEd9olvLtWwanvTITqJREZLrGF5TZPo4qMCebgjS+tPoiyXdTd2s7nrgXQm97aD8juLiHPp1UlYKaihbPXAnon1uj99dr0JVevqz1//aYEF3qo9Z2SPM=

script:
  - make buildAll

deploy:
  provider: script
  script: make pushAll
  on:
    branch: master
